import '../l10n/app_localizations.dart';

/// A country entry: ISO 3166-1 alpha-2 code plus display names.
///
/// The code is the wire format shared with the backend (`nationality` tag);
/// the names are for display only.
typedef Country = ({String code, String de, String en});

/// Countries offered in the nationality picker. The list covers Europe
/// comprehensively plus major countries worldwide; codes are what the
/// backend expects, so extending the list never breaks existing data.
const List<Country> countries = [
  (code: 'AL', de: 'Albanien', en: 'Albania'),
  (code: 'DZ', de: 'Algerien', en: 'Algeria'),
  (code: 'AD', de: 'Andorra', en: 'Andorra'),
  (code: 'AR', de: 'Argentinien', en: 'Argentina'),
  (code: 'AM', de: 'Armenien', en: 'Armenia'),
  (code: 'AU', de: 'Australien', en: 'Australia'),
  (code: 'AT', de: 'Österreich', en: 'Austria'),
  (code: 'AZ', de: 'Aserbaidschan', en: 'Azerbaijan'),
  (code: 'BH', de: 'Bahrain', en: 'Bahrain'),
  (code: 'BD', de: 'Bangladesch', en: 'Bangladesh'),
  (code: 'BY', de: 'Belarus', en: 'Belarus'),
  (code: 'BE', de: 'Belgien', en: 'Belgium'),
  (code: 'BA', de: 'Bosnien und Herzegowina', en: 'Bosnia and Herzegovina'),
  (code: 'BR', de: 'Brasilien', en: 'Brazil'),
  (code: 'BG', de: 'Bulgarien', en: 'Bulgaria'),
  (code: 'CA', de: 'Kanada', en: 'Canada'),
  (code: 'CL', de: 'Chile', en: 'Chile'),
  (code: 'CN', de: 'China', en: 'China'),
  (code: 'CO', de: 'Kolumbien', en: 'Colombia'),
  (code: 'CR', de: 'Costa Rica', en: 'Costa Rica'),
  (code: 'HR', de: 'Kroatien', en: 'Croatia'),
  (code: 'CY', de: 'Zypern', en: 'Cyprus'),
  (code: 'CZ', de: 'Tschechien', en: 'Czechia'),
  (code: 'DK', de: 'Dänemark', en: 'Denmark'),
  (code: 'DO', de: 'Dominikanische Republik', en: 'Dominican Republic'),
  (code: 'EC', de: 'Ecuador', en: 'Ecuador'),
  (code: 'EG', de: 'Ägypten', en: 'Egypt'),
  (code: 'SV', de: 'El Salvador', en: 'El Salvador'),
  (code: 'EE', de: 'Estland', en: 'Estonia'),
  (code: 'ET', de: 'Äthiopien', en: 'Ethiopia'),
  (code: 'FI', de: 'Finnland', en: 'Finland'),
  (code: 'FR', de: 'Frankreich', en: 'France'),
  (code: 'GE', de: 'Georgien', en: 'Georgia'),
  (code: 'DE', de: 'Deutschland', en: 'Germany'),
  (code: 'GH', de: 'Ghana', en: 'Ghana'),
  (code: 'GR', de: 'Griechenland', en: 'Greece'),
  (code: 'GT', de: 'Guatemala', en: 'Guatemala'),
  (code: 'HN', de: 'Honduras', en: 'Honduras'),
  (code: 'HU', de: 'Ungarn', en: 'Hungary'),
  (code: 'IS', de: 'Island', en: 'Iceland'),
  (code: 'IN', de: 'Indien', en: 'India'),
  (code: 'ID', de: 'Indonesien', en: 'Indonesia'),
  (code: 'IR', de: 'Iran', en: 'Iran'),
  (code: 'IQ', de: 'Irak', en: 'Iraq'),
  (code: 'IE', de: 'Irland', en: 'Ireland'),
  (code: 'IL', de: 'Israel', en: 'Israel'),
  (code: 'IT', de: 'Italien', en: 'Italy'),
  (code: 'JM', de: 'Jamaika', en: 'Jamaica'),
  (code: 'JP', de: 'Japan', en: 'Japan'),
  (code: 'JO', de: 'Jordanien', en: 'Jordan'),
  (code: 'KZ', de: 'Kasachstan', en: 'Kazakhstan'),
  (code: 'KE', de: 'Kenia', en: 'Kenya'),
  (code: 'KW', de: 'Kuwait', en: 'Kuwait'),
  (code: 'KG', de: 'Kirgisistan', en: 'Kyrgyzstan'),
  (code: 'LV', de: 'Lettland', en: 'Latvia'),
  (code: 'LB', de: 'Libanon', en: 'Lebanon'),
  (code: 'LY', de: 'Libyen', en: 'Libya'),
  (code: 'LI', de: 'Liechtenstein', en: 'Liechtenstein'),
  (code: 'LT', de: 'Litauen', en: 'Lithuania'),
  (code: 'LU', de: 'Luxemburg', en: 'Luxembourg'),
  (code: 'MY', de: 'Malaysia', en: 'Malaysia'),
  (code: 'MT', de: 'Malta', en: 'Malta'),
  (code: 'MX', de: 'Mexiko', en: 'Mexico'),
  (code: 'MD', de: 'Moldau', en: 'Moldova'),
  (code: 'MC', de: 'Monaco', en: 'Monaco'),
  (code: 'ME', de: 'Montenegro', en: 'Montenegro'),
  (code: 'MA', de: 'Marokko', en: 'Morocco'),
  (code: 'MZ', de: 'Mosambik', en: 'Mozambique'),
  (code: 'MM', de: 'Myanmar', en: 'Myanmar'),
  (code: 'NA', de: 'Namibia', en: 'Namibia'),
  (code: 'NP', de: 'Nepal', en: 'Nepal'),
  (code: 'NL', de: 'Niederlande', en: 'Netherlands'),
  (code: 'NZ', de: 'Neuseeland', en: 'New Zealand'),
  (code: 'NI', de: 'Nicaragua', en: 'Nicaragua'),
  (code: 'NG', de: 'Nigeria', en: 'Nigeria'),
  (code: 'MK', de: 'Nordmazedonien', en: 'North Macedonia'),
  (code: 'NO', de: 'Norwegen', en: 'Norway'),
  (code: 'OM', de: 'Oman', en: 'Oman'),
  (code: 'PK', de: 'Pakistan', en: 'Pakistan'),
  (code: 'PA', de: 'Panama', en: 'Panama'),
  (code: 'PY', de: 'Paraguay', en: 'Paraguay'),
  (code: 'PE', de: 'Peru', en: 'Peru'),
  (code: 'PH', de: 'Philippinen', en: 'Philippines'),
  (code: 'PL', de: 'Polen', en: 'Poland'),
  (code: 'PT', de: 'Portugal', en: 'Portugal'),
  (code: 'QA', de: 'Katar', en: 'Qatar'),
  (code: 'RO', de: 'Rumänien', en: 'Romania'),
  (code: 'RU', de: 'Russland', en: 'Russia'),
  (code: 'SA', de: 'Saudi-Arabien', en: 'Saudi Arabia'),
  (code: 'SN', de: 'Senegal', en: 'Senegal'),
  (code: 'RS', de: 'Serbien', en: 'Serbia'),
  (code: 'SG', de: 'Singapur', en: 'Singapore'),
  (code: 'SK', de: 'Slowakei', en: 'Slovakia'),
  (code: 'SI', de: 'Slowenien', en: 'Slovenia'),
  (code: 'ZA', de: 'Südafrika', en: 'South Africa'),
  (code: 'KR', de: 'Südkorea', en: 'South Korea'),
  (code: 'ES', de: 'Spanien', en: 'Spain'),
  (code: 'LK', de: 'Sri Lanka', en: 'Sri Lanka'),
  (code: 'SE', de: 'Schweden', en: 'Sweden'),
  (code: 'CH', de: 'Schweiz', en: 'Switzerland'),
  (code: 'SY', de: 'Syrien', en: 'Syria'),
  (code: 'TW', de: 'Taiwan', en: 'Taiwan'),
  (code: 'TZ', de: 'Tansania', en: 'Tanzania'),
  (code: 'TH', de: 'Thailand', en: 'Thailand'),
  (code: 'TN', de: 'Tunesien', en: 'Tunisia'),
  (code: 'TR', de: 'Türkei', en: 'Türkiye'),
  (code: 'UA', de: 'Ukraine', en: 'Ukraine'),
  (code: 'AE', de: 'Vereinigte Arabische Emirate', en: 'United Arab Emirates'),
  (code: 'GB', de: 'Vereinigtes Königreich', en: 'United Kingdom'),
  (code: 'US', de: 'Vereinigte Staaten', en: 'United States'),
  (code: 'UY', de: 'Uruguay', en: 'Uruguay'),
  (code: 'UZ', de: 'Usbekistan', en: 'Uzbekistan'),
  (code: 'VE', de: 'Venezuela', en: 'Venezuela'),
  (code: 'VN', de: 'Vietnam', en: 'Vietnam'),
  (code: 'YE', de: 'Jemen', en: 'Yemen'),
];

/// Returns the localized display name for [code], or the uppercased code
/// itself when it is unknown (e.g. data from before normalization).
String countryDisplayName(AppLocalizations l10n, String code) {
  for (final country in countries) {
    if (country.code == code.toUpperCase()) {
      return l10n.localeName == 'de' ? country.de : country.en;
    }
  }
  return code.toUpperCase();
}
